services:
  # Security-enhanced proxy for the Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: always
    networks:
      socket-proxy:
        ipv4_address: 192.168.91.254
    privileged: true
    ports:
      - "127.0.0.1:2375:2375" # DO NOT EXPOSE THIS PORT (2375) TO INTERNET (port forwarding, etc)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=info
      # Configure access to Docker API
      # 0 = revoke, 1 = grant
      # See: https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#grant-or-revoke-access-to-certain-api-sections
      # ---
      # Granted by default (mostly harmless)
      - EVENTS=1 # Required for: Dozzle
      - PING=1
      - VERSION=1
      # Denied by default (security-critical)
      - AUTH=0
      - SECRETS=0
      - POST=1 # Required for: Watchtower
      # Not so critical
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Required for: Traefik, Homepage, Dozzle, Watchtower
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Required for: Watchtower
      - INFO=1 # Required for: Dozzle
      - NETWORKS=1 # Required for: Watchtower
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=1 # Required for: Watchtower