services:
  # Movie Manager (4K)
  radarr-4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-4k
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_DIR}/radarr-4k:/config
      - ${LOG_DIR}/radarr-4k:/config/logs
      - ${DATA_DIR}:/data
    networks:
      - radarr-4k
      - prowlarr
      - recyclarr
      - vpn
      - prometheus
      - homepage
      - traefik
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/ping" ]
      interval: 30s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # HTTP Routers
      - "traefik.http.routers.radarr-4k-router.entrypoints=websecure"
      - "traefik.http.routers.radarr-4k-router.rule=Host(`radarr-4k.${DOMAIN_NAME}`)"
      # Middlewares
      - "traefik.http.routers.radarr-4k-router.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.radarr-4k-router.service=radarr-4k-service"
      - "traefik.http.services.radarr-4k-service.loadbalancer.server.port=7878"

  # Prometheus Exporter
  radarr-4k-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: radarr-4k-exporter
    restart: always
    command: ["radarr"]
    environment:
      PORT: 8080
      URL: "http://localhost:7878"
      APIKEY: ${RADARR_4K_API_KEY}
    network_mode: "service:radarr-4k"
    depends_on:
      radarr-4k:
        condition:  service_healthy

networks:
  radarr-4k:
    name: radarr-4k
