services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      DOCKER_SOCK: tcp://socket-proxy:2375
      AUTOHEAL_CONTAINER_LABEL: all
    networks:
      - socket-proxy