services:
  # Real-time log viewer for Docker containers
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      DOCKER_HOST: tcp://socket-proxy:2375
    networks:
      - socket-proxy
      - traefik
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dozzle-router.entrypoints=websecure"
      - "traefik.http.routers.dozzle-router.rule=Host(`dozzle.${DOMAIN_NAME}`)"
      # Middlewares
      - "traefik.http.routers.dozzle-router.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.dozzle-router.service=dozzle-service"
      - "traefik.http.services.dozzle-service.loadbalancer.server.port=8080"