services:
  # Movie Manager
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_DIR}/radarr:/config
      - ${LOG_DIR}/radarr:/config/logs
      - ${DATA_DIR}:/data
    networks:
      - radarr
      - prowlarr
      - recyclarr
      - vpn
      - prometheus
      - homepage
      - traefik
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/ping" ]
      interval: 30s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # HTTP Routers
      - "traefik.http.routers.radarr-router.entrypoints=websecure"
      - "traefik.http.routers.radarr-router.rule=Host(`radarr.${DOMAIN_NAME}`)"
      # Middlewares
      - "traefik.http.routers.radarr-router.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.radarr-router.service=radarr-service"
      - "traefik.http.services.radarr-service.loadbalancer.server.port=7878"

  # Prometheus Exporter
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: radarr-exporter
    restart: always
    command: ["radarr"]
    environment:
      PORT: 8080
      URL: "http://localhost:7878"
      APIKEY: ${RADARR_API_KEY}
    network_mode: "service:radarr"
    depends_on:
      radarr:
        condition:  service_healthy

networks:
  radarr:
    name: radarr
