services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${APPDATA_DIR}/prometheus:/prometheus
    networks:
      - prometheus

networks:
  prometheus:
    name: prometheus
